spring:
    profiles: 
    active: 
    - dev
---
spring:
    profiles: dev
    application: 
        name: microservicecloud-config-suyu-dev
---
spring:
    profiles: test
    application: 
        name: microservicecloud-config-suyu-test